on:
  push:
    branches: [master]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

name: pytest

jobs:
  uv-pytest:
    name: python
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-groups

      - name: Setup Dapr CLI default version
        uses: dapr/setup-dapr@v1
        id: install-dapr
        with:
          version: "1.16.1"

      - name: Initialize Dapr
        run: |
          dapr init
          dapr --version

      - name: Run tests using pytest
        run: uv run --group test pytest -v tests/
